### ISSUE TITLE
Write stream optional?

### ISSUE THREAD

**Issue by andredublin** [twilson63/palmettoflow#3]
The write stream seems to be an integral part to the whole system, and given the flexibility of the flow architecture.  Would write stream be considered optional? So instead of having some kind of intermediary log, push writes to services and services respond to components?

**Comment by twilson63** [comment]
Its worth talking about, the problems the write log solves are the following:
- service registry (you don't have to know where each service is registered to subscribe, you just need to know the location of the write log.
- migrations, since the write log contains a full event history it is simple to build new data services by replaying the log, so migrations are very easy to reason about.
- ability to re-use services for several applications.  

I think the beauty of the write log is that it turns your services and components into legos, it is easy to swap a service containing photos from local disk, to s3, to other blob driven services without any changes to any other application logic.  you experiment with different persistent engines for your data services to use the best available without having to re-write the app,  You could use mongodb for one data service and mysql for another and neo4j for another without any concern of incompatibility.  

The last thing is compose-ability or streams - the ability to chain, fan out, fan in, etc.

How would you manage these issues without a central log, and keep things simple in the components and services side?

**Comment by andredublin** [comment]
Ok, I understand now the intent of the write log.  In my current websocket application is so simple, I have no need and do not foresee in the future for multiple data services.
